name: Basic Tests

on:
  pull_request:
    branches: [ main ]
  # Allow manual dispatch
  workflow_dispatch:

jobs:
  html-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install html-validator
        run: npm install -g html-validator-cli
      
      - name: Validate HTML
        run: html-validator --file index.html --verbose
      
      - name: Check for broken links
        run: |
          npm install -g broken-link-checker
          blc http://localhost:8080 -ro --exclude linkedin.com --exclude github.com --exclude twitter.com
        continue-on-error: true
